# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ESSI::FileSetMetadata
  include ESSI::RemoteLookupMetadata
  include ::Hyrax::FileSetBehavior

  directly_contains_one :preservation_master_file, through: :files, type: ::RDF::URI('http://pcdm.org/use#PreservationMasterFile'), class_name: 'Hydra::PCDM::File'

  self.indexer = ESSI::FileSetIndexer

  def collection_branding_info
    @collection_branding_info ||= CollectionBrandingInfo.where(file_set_id: self.id).first
  end

  def collection_branding?
    collection_branding_info.present?
  end

  def ocr_language
    [language.entries,
     parent&.language&.entries,
     ESSI.config.dig(:essi, :ocr_language),
     'eng'].map { |l| Tesseract.try_languages(l) }.select(&:present?).first
  end

  # @todo revisit after Hyrax 3.x upgrade
  # copied from Hyrax::FileSetIndexer to provide a common interface across:
  # - FileSet
  # - SolrDocument
  # - Hyrax::FileSetPresenter, initialized with either of above
  def original_file_id
    @original_file_id ||= begin
      return unless self.original_file
      if self.original_file.versions.present?
        ActiveFedora::File.uri_to_id(self.current_content_version_uri)
      else
        self.original_file.id
      end
    end
  end
end
