# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  # FIXME: this is a workaround for all_text_timv that officially has an ASCII encoding,
  # but contains UTF-8 extended characters.  But it would be good to poke more into the
  # stack to figure out where the encoding is being set wrongly, in the first place
  def to_solr(solr_doc = {})
    super.tap do |doc|
      doc['all_text_timv'] = doc['all_text_timv'].force_encoding('utf-8') if doc['all_text_timv'].is_a? String
    end
  end
end
